apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: genai-photo-generator
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/nvinto-ocm-tenant/genai-photo-generator/genai-photo-generator@sha256:21711605c7673f5125fadbc5204b39c070a46977c7395a07f95e8a764642677a
        name: my-python
        resources: {}
status: {}
