apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: genai-photo-generator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: genai-photo-generator
    app.kubernetes.io/part-of: genai-photo-generator
  name: genai-photo-generator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: genai-photo-generator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: genai-photo-generator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/nvinto-ocm-tenant/genai-photo-generator/genai-photo-generator@sha256:275be4fd5069bfc7b1c86d95bfda5b68092230a362c6bc3eb12bacf5595af130
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
