apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: genai-photo-generator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: genai-photo-generator
    app.kubernetes.io/part-of: genai-photo-generator
  name: genai-photo-generator
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: genai-photo-generator
status:
  loadBalancer: {}
