apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: genai-photo-generator
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/nvinto-ocm-tenant/genai-photo-generator/genai-photo-generator@sha256:60b4bf2a2074405bb6f5910a6189bdec1c9d1234aa3bd8a4126f306a09530a42
        name: my-python
        resources: {}
status: {}
